[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["npx prisma generate", "npx next build"]

[start]
cmd = "npx prisma db push --accept-data-loss && npx next start -p ${PORT:-3000}"
